### ISSUE TITLE
Unable to start Activities front

### ISSUE THREAD

**Issue by jeantil** [swcraftlyon/meetup#27]
```
$> npm install
```

worked fine

```
$> npm run serve

> @ serve /Users/jean/dev/websites/meetup/Activities/WebApp
> gulp serve


/Users/jean/dev/websites/meetup/Activities/WebApp/conf/gulp.conf.js:11
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jean/dev/websites/meetup/Activities/WebApp/gulpfile.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

```
$> npm -v
1.3.14
```

**Comment by nicolaspayot** [comment]
It doesn't work with npm versions < 3.x.x. I got the same error with v2.14.9. It works fine with v3.3.12. I should probably mention it on the readme file. You should look at nvm (https://github.com/creationix/nvm) to switch node / npm versions on the fly. That's what I'm using, it's pretty cool.
